### ISSUE TITLE
Code executing without errors but not detecting corners

### ISSUE THREAD

**Issue by TehseenHasan** [ObeidaElJundi/Camera-Calibration#2]
![image](https://user-images.githubusercontent.com/25352528/97072355-d042a280-15f9-11eb-86ba-a97d196777bc.png)

The code is **executing without any error**. The GUI windows show I clicked on `Detect Corners` then press the Start button then bring the checkerboard in front of the camera but **nothing happens**. The code d**oes not detect** corners at all. What is the problem? I am using Anaconda IDE (Spyder IDE) and Python 3.8. I have installed all the requirements libraries (all new versions - old version as specified in the requirements.txt are not installing on my IDE). 
Now where is the problem?

**Comment by TehseenHasan** [comment]
I think I **solved the issue**. The problem was that I have to enter the number of rows and columns of my Checkerboard in your code manually at line: Here (6,8) means 6 rows and 8 columns https://github.com/ObeidaElJundi/Camera-Calibration/blob/f3687119d1cbee366dcd39507f77325b408d0fe1/calibration_GUI.py#L196 
and at this line https://github.com/ObeidaElJundi/Camera-Calibration/blob/f3687119d1cbee366dcd39507f77325b408d0fe1/calibration_GUI.py#L199

I also changed the number of columns and rows on thins line: https://github.com/ObeidaElJundi/Camera-Calibration/blob/f3687119d1cbee366dcd39507f77325b408d0fe1/calibration_GUI.py#L29

To change the Square size according to my checkerboard. I think I have to enter the size in this line: https://github.com/ObeidaElJundi/Camera-Calibration/blob/f3687119d1cbee366dcd39507f77325b408d0fe1/calibration_GUI.py#L30
**is the x, y is the size of checkerboard squares (in millimeters)?**

### Am I right?

- And should I specify the resolution of my image frame (e.g 640x480) manually in the code or the code gets the resolution itself?
- And the last question, is there any other place (other than the places I mentioned above) in code where I have to change the rows and columns value of my checkerboard?

**Comment by TehseenHasan** [comment]
I have updated the code of the `calibration_GUI.py` file and submit a pull request having some changes where I applied configuration variables for custom Checkerboards. Please check that and if It is OK then merge it thanks. 
https://github.com/ObeidaElJundi/Camera-Calibration/pull/3#issue-509434607

**Comment by ObeidaElJundi** [comment]
Merged! Thanks 👍
